config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/', to: 'pokemons#index'
  get '/abilities', to: 'abilities#index'
  get '/types', to: 'types#index'
  get '/about', to: 'about#show'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :pokemons
  resources :abilities
  resources :types

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/abilities_pokemons.rb
class AbilitiesPokemons < ApplicationRecord
end

app/models/ability.rb
class Ability < ApplicationRecord
    has_and_belongs_to_many :pokemons

    validates :name, presence: true
    validates :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_and_belongs_to_many :types
    has_and_belongs_to_many :abilities

    validates :name, presence: true
    validates :generation, presence: true

    def self.search(search)
        if search
            pokemon = Pokemon.find_by(name: search)
                if pokemon
                    self.where(id: pokemon)
                else
                    @pokemons = Pokemon.all
                end
            else
                @pokemons = Pokemon.all
            end
        end
end

app/models/pokemons_types.rb
class PokemonsTypes < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
    has_and_belongs_to_many :pokemons

    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
    def index
        @abilities = Ability.all.page(params[:page])
    end
    def show
        @ability = Ability.find(params[:id])
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def show
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    def index
        @pokemons = Pokemon.search(params[:search]).page(params[:page])
    end
    def show
        @pokemon = Pokemon.find(params[:id])
    end

    private

    def pokemon_params
        params_require(:pokemon).permit(:name, :height, :weight, :evolves_from, :url, :generation)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
    def index
        @types = Type.all
    end
    def show
        @type = Type.find(params[:id])
    end
end

app/helpers/ability_helper.rb
module AbilityHelper
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/helpers/type_helper.rb
module TypeHelper
end

app/views/abilities/index.html.erb
<h1>Abilities</h1>

<% @abilities.each do |ability| %>
    <ul>
    <%= link_to ability.name, ability %>
    </ul>
<% end %>

<%= paginate @abilities %>

app/views/abilities/show.html.erb
<h1><%= @ability.name %></h1>

<%= link_to "Back", abilities_path %>

<p><%= @ability.description %></p>

<% @ability.pokemons.each do |poke_ab| %>
    <%= link_to poke_ab.name, poke_ab %>
    </br>
<% end %>

app/views/about/show.html.erb
<div class='about-container'>

<div>
	<h1 class='about-title'>Database ERD</h1>
	<%= image_tag "ERD_poke_api.png" %>
</div>

<div>
<h1 class='about-title'>Describe Dataset</h1>
<div class='about-paragraph'>
<p>I'm going to use the pokemon_api and their numerous endpoints to populate three tables, 
pokemon, types and abilities.</p>

<p>A pokemon can have types, a type can have multiple pokemons. 
A pokemon can have abilities, an ability can be in multiple pokemons.</p>

<p>To populate pokemon table  I'm going to use the pokemon, pokemon-species and generation endpoints. 
To populate types table  I'm gonna use the type endpoint. To populate abilities table 
I'm going to use the ability endpoint.</p>

<p>There are two many to many associations that create the tables pokemons_types and abilities_pokemons, 
so you can see a list of pokemon depending their type, and a list of abilities for each pokemon.
</p>
</div>
</div>

<div>
<h4>Table Pokemon</h4>
<p>
	<p>name: https://pokeapi.co/api/v2/pokemon?limit=300</p>
	<p>height: https://pokeapi.co/api/v2/pokemon/{name}</p>
	<p>weight: https://pokeapi.co/api/v2/pokemon/{name}</p>
	<p>url: https://pokeapi.co/api/v2/pokemon/{name}</p>
	<p>color: https://pokeapi.co/api/v2/pokemon-species/{name}/</p>
	<p>evolves_from https://pokeapi.co/api/v2/pokemon-species/{name}/</p>
	<p>generation: https://pokeapi.co/api/v2/pokemon-species/{name}/ -> https://pokeapi.co/api/v2/generation/id/</p>
</p>
</div>


<div>
<h4>Table Types</h4>
	<p>name: https://pokeapi.co/api/v2/type?limit=50</p>
</div>

<div>
<h4>Table Ability</h4>
	<p>name: https://pokeapi.co/api/v2/ability?limit=300</p>
	<p>description: https://pokeapi.co/api/v2/ability/{name}/</p>
</div>
	
<div>
<h4>Table Pokemons_Types</h4>
<p>type_name (types)</p>
<p>pokemon_name (pokemon)</p>
</div>

<div>
<h4>Table Abilities_Pokemons</h4>
<p>ability_name (ability)</p>
<p>pokemon_name (pokemon)</p>
</div>

</div>

app/views/layouts/_navbar.html.erb
<header>

    <div class='container'>

        <nav>
            <ul>
            <li><%= link_to "Pokemon", "/" %></li>
            <% if user_signed_in? %>           
            <li><%= link_to "Abilities", abilities_path %></li>
            <li><%= link_to "Types", types_path %></li>
            <% end %>
            <li><%= link_to "About", about_path %></li>
            <% if user_signed_in? %>
                <li>You are logged in as: <%= current_user.email %><%= link_to ' Sign out', destroy_user_session_path, data: { turbo_method: :delete } %></li>
                    <% else %>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
            <% end %>
            </ul>
        </nav>

    </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<h1>Pokemons</h1>

<%= form_tag "/", :method => "get" do %>
    <%= label_tag(:search, "Search for a Pokemon") %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag("Search", :name => nil) %>
<% end %>

<% @pokemons.each do |pokemon| %>
    <% if user_signed_in? %>
        <ul>
            <%= link_to pokemon.name, pokemon %>
            <% unless pokemon.url.blank? %>
                <%= image_tag pokemon.url %>
            <% end %>
        </ul>
        <% else %>
            <%= pokemon.name %>
            <% unless pokemon.url.blank? %>
                <%= image_tag pokemon.url %>
            <% end %>
        <% end %> 
<% end %>

<%= paginate @pokemons %>

app/views/pokemons/show.html.erb
<h1><%= @pokemon.name %></h1>

<%= link_to "Back", "/" %>


<%= image_tag @pokemon.url %>

<p><%= @pokemon.height %></p>
<p><%= @pokemon.weight %></p>
<p><%= @pokemon.color %></p>
<p><%= @pokemon.evolves_from %></p>
<p><%= @pokemon.generation %></p>

<p>

Pokemon Types:
</br>
</br>
<% @pokemon.types.each do |poke_type| %>
    <label><%= poke_type.name %></label>
    </br>
    <% end %>

</br>
</br>
</br>

Pokemon Abilities:
</br>
</br>
<% @pokemon.abilities.each do |poke_abs| %>
    <label><%= poke_abs.name %></label>
    </br>
    <label><%= poke_abs.description %></label>
    </br>
    </br>
    <% end %>

</p>

app/views/types/index.html.erb
<h1>Types</h1>

<% @types.each do |type| %>
    <ul>
    <%= link_to type.name, type %>
    </ul>
<% end %>

app/views/types/show.html.erb
<h1><%= @type.name %></h1>

<%= link_to "Back", types_path %>

</br>

<% @type.pokemons.each do |poke_type| %>
    <%= image_tag poke_type.url %>
    <%= link_to poke_type.name, poke_type %>
    </br>
<% end %>